config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/:username', to: 'github_profiles#show'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_repo.rb
class GithubRepo
  attr_reader :name, :link, :language

  def initialize(attrs)
    @name = attrs[:name]
    @link = attrs[:html_url]
    @language = attrs[:language]
  end
end

app/models/github_user.rb
class GithubUser
  attr_reader :name,
              :username,
              :picture,
              :email,
              :location,
              :bio,
              :followers,
              :following,
              :public_repos

  def initialize(attrs, url_username)
    @url_username = url_username
    @name = attrs[:name]
    @username = attrs[:login]
    @email = attrs[:email]
    @location = attrs[:location]
    @picture = attrs[:avatar_url]
    @bio = attrs[:bio]
    @followers = attrs[:followers]
    @following = attrs[:following]
    @public_repos = attrs[:public_repos]
    @repos = []
  end

  def repos
    @repos = GithubRepoService.new(@url_username).repos
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :generate_slug

  def generate_slug
    self.slug = username.parameterize
  end

  def to_params
    slug
  end

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid = auth_info.uid
      new_user.name = auth_info.extra.raw_info.name
      new_user.username = auth_info.info.nickname
      new_user.oauth_token = auth_info.credentials.token
    end
  end

  # def self.from_omniauth(auth_info)
  #   where(uid: auth_info[:uid]).first_or_create do |new_user|
  #     new_user.uid = auth_info.uid
  #     new_user.name = auth_info.extra.raw_info.name
  #     new_user.username = auth_info.info.nickname
  #   end
  #   update(oauth_token: auth_info.credentials.token)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(uid: session[:user_id]) if session[:user_id]
  end
end

app/controllers/github_profiles_controller.rb
class GithubProfilesController < ApplicationController
  def show
    @github_profile ||= GithubUserService.new(params[:username], current_user).profile
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.uid
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github_profiles/show.html.erb
<div class='show_body'>

  <section class="bio_info">
    <div class="pic">
      <%= image_tag @github_profile.picture %>
    </div>

    <div class="bio-text">
      <table>

        <tr>
          <th class='info'></th>
          <th class='info'></th>
        </tr>

        <tr class="name">
          <td class='info-h'>Name </td>
          <td class='info'><%= @github_profile.name %></td>
        </tr>

        <tr class="username">
          <td class='info-h'>Username </td>
          <td class='info'><%= @github_profile.username %></td>
        </tr>

        <tr class="email">
          <td class='info-h'>Email</td>
          <td class='info'><%= @github_profile.email %></td>
        </tr>

        <tr class="location">
          <td class='info-h'>Location</td>
          <td class='info'><%= @github_profile.location %></td>
        </tr>

        <tr class="bio">
          <td class='info-h'>Bio</td>
          <td class='info'><%= @github_profile.bio %></td>
        </tr>

        <tr class="followers">
          <td class='info-h'>Followers</td>
          <td class='info'><%= @github_profile.followers %></td>
        </tr>

        <tr class="following">
          <td class='info-h'>Following</td>
          <td class='info'><%= @github_profile.following %></td>
        </tr>

        <tr class="public_repos">
          <td class='info-h'>Repos</td>
          <td class='info'><%= @github_profile.public_repos %></td>
        </tr>
      </table>
    </div>
  </section>

  <section class='main_repos'>
    <% @github_profile.repos.each do |repo| %>
      <div class='repo'>

        <div class='repo_item'>
          REPO<%= link_to "#{repo.name}", repo.link %>
        </div>

        <div class='repo_item'>
          <p>Language: <%= repo.language %></p>
        </div>

      </div>
    <% end %>
  </section>
</div>

app/views/layouts/_nav.html.erb
<nav class='nav'>
  <div class="empty">
  </div>
  <div class='title'>
    <h1>API CURIOUS</h1>
  </div>
  <div class='login'>
    <% if current_user %>
      <%= link_to 'Logout', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'Login With Github', github_login_path %>
    <% end %>
  <div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiCurious - <%= params['username'] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<section class='main-welcome'>
  <section class='welcome-card'>
    <% if current_user %>
      <h1>Hello, <%= current_user.name %>.</h1>

      <br>
      <%= link_to "Visit Your Profile Here", "/#{current_user.username}" %>
    <% else %>
      <p>Please Sign In.</p>
    <% end %>
  </section>
</section>